// redux-api-middleware FSAs
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_UNDO_TASKS_REQUEST = 'GET_UNDO_TASKS_REQUEST';
export const GET_UNDO_TASKS_SUCCESS = 'GET_UNDO_TASKS_SUCCESS';
export const GET_UNDO_TASKS_FAILURE = 'GET_UNDO_TASKS_FAILURE';

export const GET_COMPLETE_TASKS_REQUEST = 'GET_COMPLETE_TASKS_REQUEST';
export const GET_COMPLETE_TASKS_SUCCESS = 'GET_COMPLETE_TASKS_SUCCESS';
export const GET_COMPLETE_TASKS_FAILURE = 'GET_COMPLETE_TASKS_FAILURE';
